server:
  port: 8081
spring:
  profiles:
    active: prod

---
spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tradingdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  rabbitmq:
    host: 3.145.30.125
    port: 5672
    username: guest
    password: guest
  redis:
    config:
      hostname: 3.145.30.125
      port: 6379
      password: TeamToukunya
      topic: validations
